name: GitHub CI
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linux64_build:
    name: Linux x86_64 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker run -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
      - name: Package
        run: tar czf subconverter_linux64.tar.gz subconverter
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux64
          path: subconverter_linux64.tar.gz

  arm64_build:
    name: Linux ARM64 Build
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker run -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:aarch64-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
      - name: Package
        run: tar czf subconverter_arm64.tar.gz subconverter
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: arm64
          path: subconverter_arm64.tar.gz
